### ISSUE TITLE
出现一个很奇怪的问题，角标越界

### ISSUE THREAD

**Issue by dicallc** [ihsg/PatternLocker#17]
#5707 java.lang.IndexOutOfBoundsException
Invalid index 1117126656, size is 9
com.github.ihsg.patternlocker.h.a(DefaultLockerLinkedLineView.java:70)

**Comment by ihsg** [comment]
@dicallc 谢谢反馈, 使用的是最新版本么?

**Comment by dicallc** [comment]
不是最新的哦  2.1.0的

**Comment by dicallc** [comment]
升级到2.2.0出现下面错误
```
    java.lang.NoClassDefFoundError: Failed resolution of: [Lkotlin/reflect/KProperty;
        at com.github.ihsg.patternlocker.PatternIndicatorView.<clinit>(PatternIndicatorView.kt)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.fbi.bitcloud.login.pattern.PatternSettingFragment.initViews(PatternSettingFragment.java:82)
        at com.fbi.bitcloud.base.BaseFragment.onCreateView(BaseFragment.java:58)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
        at android.app.Activity.performStart(Activity.java:6295)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2406)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2503)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.reflect.KProperty" 
```

**Comment by dicallc** [comment]
我项目并没有用kotlin

**Comment by ihsg** [comment]
@dicallc 是不是没有依赖jitpack？
项目根目录下的 build.gradle，添加jitpack仓库地址
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
